/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/models/blackhole.gltf
Author: NestaEric (https://sketchfab.com/Nestaeric)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-hole-e410da98b1e5445eae2acafaaa53587d
Title: Black Hole
*/

import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';

export default function Model(props) {
  const group = useRef();
  const { scene } = useGLTF('../../../models/models/earth.gltf');

  // Rotate the model on each frame
  useFrame(() => {
    if (group.current) {
      // group.current.rotation.x += 0.01; // Rotate around X-axis
      group.current.rotation.y += 0.0002; // Rotate around Y-axis
    }
  });

  return (
    <group ref={group} {...props}>
      <primitive object={scene}/>
    </group>
  );
}
