/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.0 public/models/models/blackhole.gltf
Author: NestaEric (https://sketchfab.com/Nestaeric)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/black-hole-e410da98b1e5445eae2acafaaa53587d
Title: Black Hole
*/

import React, { useRef, useMemo, useState, useEffect } from 'react';
import { useGLTF, useScroll } from '@react-three/drei';
import { useFrame } from '@react-three/fiber';
import * as THREE from 'three';

export default function Earth() {
  const group = useRef();
  const [initialPosition] = useState(new THREE.Vector3(0.5, 0, 0)); // X = 0.3, Y = 0, Z = 0
  const { scene } = useGLTF('../../../models/models/earth.gltf');
  const scroll = useScroll();

  useFrame(() => {
    if (group.current) {
      // Keep rotating the model
      group.current.rotation.y += 0.0002; // Rotate around Y-axis

      // Update the position relative to the initial position
      const xPos = initialPosition.x + ((-scroll.offset * 3) * 1.2);
      group.current.position.set(xPos, initialPosition.y, initialPosition.z); // Maintain Y and Z values

      // console.log(group.current.position.y);
    }
  });

  return (
    <group ref={group} rotation={[0, 0, -0.2604]} >
      <primitive object={scene} scale={[1, 1, 1]}/>
    </group>
  );
}
